"""add independence disclosures and conflict overrides

Revision ID: 0b477a84ab3f
Revises: e5f6a7b8c9d0
Create Date: 2026-08-19 17:39:06.697219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b477a84ab3f'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('independence_disclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('disclosure_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_email', sa.String(length=255), nullable=True),
    sa.Column('resolved_by_name', sa.String(length=255), nullable=True),
    sa.Column('created_by_email', sa.String(length=255), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('independence_disclosures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_independence_disclosures_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_independence_disclosures_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_independence_disclosures_disclosure_type'), ['disclosure_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_independence_disclosures_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_independence_disclosures_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_independence_disclosures_user_id'), ['user_id'], unique=False)

    op.create_table('conflict_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('disclosure_ids', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('overridden_by_email', sa.String(length=255), nullable=False),
    sa.Column('overridden_by_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflict_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflict_overrides_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflict_overrides_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflict_overrides_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflict_overrides_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conflict_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflict_overrides_user_id'))
        batch_op.drop_index(batch_op.f('ix_conflict_overrides_project_id'))
        batch_op.drop_index(batch_op.f('ix_conflict_overrides_id'))
        batch_op.drop_index(batch_op.f('ix_conflict_overrides_client_id'))

    op.drop_table('conflict_overrides')
    with op.batch_alter_table('independence_disclosures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_independence_disclosures_user_id'))
        batch_op.drop_index(batch_op.f('ix_independence_disclosures_status'))
        batch_op.drop_index(batch_op.f('ix_independence_disclosures_id'))
        batch_op.drop_index(batch_op.f('ix_independence_disclosures_disclosure_type'))
        batch_op.drop_index(batch_op.f('ix_independence_disclosures_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_independence_disclosures_client_id'))

    op.drop_table('independence_disclosures')
    # ### end Alembic commands ###
