"""add workpapers and workpaper review events

Revision ID: 12d18430ab60
Revises: 0b477a84ab3f
Create Date: 2026-08-19 19:12:56.858972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d18430ab60'
down_revision: Union[str, Sequence[str], None] = '0b477a84ab3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workpapers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('preparer_id', sa.Integer(), nullable=False),
    sa.Column('prepared_by_email', sa.String(length=255), nullable=False),
    sa.Column('prepared_by_name', sa.String(length=255), nullable=False),
    sa.Column('submitted_for_review_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_email', sa.String(length=255), nullable=True),
    sa.Column('reviewed_by_name', sa.String(length=255), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('partner_status', sa.String(length=20), nullable=True),
    sa.Column('partner_signed_off_at', sa.DateTime(), nullable=True),
    sa.Column('partner_by_email', sa.String(length=255), nullable=True),
    sa.Column('partner_by_name', sa.String(length=255), nullable=True),
    sa.Column('partner_notes', sa.Text(), nullable=True),
    sa.Column('created_by_email', sa.String(length=255), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_records.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['preparer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workpapers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workpapers_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpapers_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpapers_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpapers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpapers_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpapers_preparer_id'), ['preparer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpapers_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpapers_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpapers_stage'), ['stage'], unique=False)

    op.create_table('workpaper_review_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workpaper_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workpaper_id'], ['workpapers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workpaper_review_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workpaper_review_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpaper_review_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workpaper_review_events_workpaper_id'), ['workpaper_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workpaper_review_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workpaper_review_events_workpaper_id'))
        batch_op.drop_index(batch_op.f('ix_workpaper_review_events_id'))
        batch_op.drop_index(batch_op.f('ix_workpaper_review_events_event_type'))

    op.drop_table('workpaper_review_events')
    with op.batch_alter_table('workpapers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workpapers_stage'))
        batch_op.drop_index(batch_op.f('ix_workpapers_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_workpapers_project_id'))
        batch_op.drop_index(batch_op.f('ix_workpapers_preparer_id'))
        batch_op.drop_index(batch_op.f('ix_workpapers_partner_id'))
        batch_op.drop_index(batch_op.f('ix_workpapers_id'))
        batch_op.drop_index(batch_op.f('ix_workpapers_file_id'))
        batch_op.drop_index(batch_op.f('ix_workpapers_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_workpapers_category'))

    op.drop_table('workpapers')
    # ### end Alembic commands ###
