"""add departments tags notes tasks notifications comments versioning

Revision ID: 383cb2005007
Revises: 687dfaa76c67
Create Date: 2026-07-25 10:18:11.755284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383cb2005007'
down_revision: Union[str, Sequence[str], None] = '687dfaa76c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('mentions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_id'), ['id'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=True)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_email'), ['user_email'], unique=False)

    op.create_table('sent_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sent_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sent_emails_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sent_emails_to_email'), ['to_email'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('client_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_notes_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_notes_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_notes_id'), ['id'], unique=False)

    op.create_table('client_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'tag_id', name='uq_client_tag')
    )
    with op.batch_alter_table('client_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_tags_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_tags_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_tags_tag_id'), ['tag_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_to_email', sa.String(length=255), nullable=True),
    sa.Column('assigned_to_name', sa.String(length=255), nullable=True),
    sa.Column('created_by_email', sa.String(length=255), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assigned_to_email'), ['assigned_to_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_clients_department_id'), ['department_id'], unique=False)
        batch_op.create_foreign_key('fk_clients_department_id_departments', 'departments', ['department_id'], ['id'])

    with op.batch_alter_table('file_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('previous_version_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_file_records_previous_version_id_file_records', 'file_records', ['previous_version_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verification_token_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_reset_token'), ['reset_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_verification_token'), ['verification_token'], unique=False)
        batch_op.create_foreign_key('fk_users_department_id_departments', 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_department_id_departments', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_verification_token'))
        batch_op.drop_index(batch_op.f('ix_users_reset_token'))
        batch_op.drop_index(batch_op.f('ix_users_department_id'))
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('verification_token_expires')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('file_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_file_records_previous_version_id_file_records', type_='foreignkey')
        batch_op.drop_column('previous_version_id')
        batch_op.drop_column('version')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clients_department_id_departments', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_clients_department_id'))
        batch_op.drop_column('department_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_client_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_to_email'))

    op.drop_table('tasks')
    with op.batch_alter_table('client_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_tags_tag_id'))
        batch_op.drop_index(batch_op.f('ix_client_tags_id'))
        batch_op.drop_index(batch_op.f('ix_client_tags_client_id'))

    op.drop_table('client_tags')
    with op.batch_alter_table('client_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_notes_id'))
        batch_op.drop_index(batch_op.f('ix_client_notes_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_client_notes_client_id'))

    op.drop_table('client_notes')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))
        batch_op.drop_index(batch_op.f('ix_tags_id'))

    op.drop_table('tags')
    with op.batch_alter_table('sent_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sent_emails_to_email'))
        batch_op.drop_index(batch_op.f('ix_sent_emails_id'))

    op.drop_table('sent_emails')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_email'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_name'))
        batch_op.drop_index(batch_op.f('ix_departments_id'))

    op.drop_table('departments')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_id'))
        batch_op.drop_index(batch_op.f('ix_comments_entity_type'))
        batch_op.drop_index(batch_op.f('ix_comments_entity_id'))
        batch_op.drop_index(batch_op.f('ix_comments_deleted_at'))

    op.drop_table('comments')
    # ### end Alembic commands ###
