"""add client portal users and pbc requests

Revision ID: 46ff272cb72b
Revises: 12d18430ab60
Create Date: 2026-08-20 00:59:42.518392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ff272cb72b'
down_revision: Union[str, Sequence[str], None] = '12d18430ab60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_portal_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_contact_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('invited_by_email', sa.String(length=255), nullable=False),
    sa.Column('invited_by_name', sa.String(length=255), nullable=False),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_contact_id'], ['client_contacts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_portal_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_portal_users_client_contact_id'), ['client_contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_users_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_portal_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_users_reset_token'), ['reset_token'], unique=False)

    op.create_table('pbc_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by_email', sa.String(length=255), nullable=True),
    sa.Column('submitted_by_name', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_email', sa.String(length=255), nullable=True),
    sa.Column('reviewed_by_name', sa.String(length=255), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('requested_by_email', sa.String(length=255), nullable=False),
    sa.Column('requested_by_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_records.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pbc_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pbc_requests_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_pbc_requests_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pbc_requests_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pbc_requests_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pbc_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pbc_requests_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pbc_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pbc_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pbc_requests_status'))
        batch_op.drop_index(batch_op.f('ix_pbc_requests_project_id'))
        batch_op.drop_index(batch_op.f('ix_pbc_requests_id'))
        batch_op.drop_index(batch_op.f('ix_pbc_requests_file_id'))
        batch_op.drop_index(batch_op.f('ix_pbc_requests_due_date'))
        batch_op.drop_index(batch_op.f('ix_pbc_requests_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_pbc_requests_category'))

    op.drop_table('pbc_requests')
    with op.batch_alter_table('client_portal_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_portal_users_reset_token'))
        batch_op.drop_index(batch_op.f('ix_client_portal_users_id'))
        batch_op.drop_index(batch_op.f('ix_client_portal_users_email'))
        batch_op.drop_index(batch_op.f('ix_client_portal_users_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_client_portal_users_client_id'))
        batch_op.drop_index(batch_op.f('ix_client_portal_users_client_contact_id'))

    op.drop_table('client_portal_users')
    # ### end Alembic commands ###
