"""baseline schema plus soft delete and indexes

Revision ID: 687dfaa76c67
Revises: 
Create Date: 2026-07-24 09:51:10.214418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687dfaa76c67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_clients_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_status'), ['status'], unique=False)

    with op.batch_alter_table('file_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_file_records_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_records_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_records_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_file_records_client_id'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_status'))
        batch_op.drop_index(batch_op.f('ix_clients_email'))
        batch_op.drop_index(batch_op.f('ix_clients_deleted_at'))
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
