"""add prospects and proposals for CRM pipeline

Revision ID: 928daeed2aa6
Revises: b0a3248de0db
Create Date: 2026-08-23 00:37:20.269587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928daeed2aa6'
down_revision: Union[str, Sequence[str], None] = 'b0a3248de0db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_email', sa.String(length=255), nullable=True),
    sa.Column('assigned_to_name', sa.String(length=255), nullable=True),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('converted_client_id', sa.Integer(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_email', sa.String(length=255), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], name=op.f('fk_prospects_assigned_to_user_id_users')),
    sa.ForeignKeyConstraint(['converted_client_id'], ['clients.id'], name=op.f('fk_prospects_converted_client_id_clients')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_prospects_department_id_departments')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prospects_assigned_to_user_id'), ['assigned_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_contact_email'), ['contact_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_converted_client_id'), ['converted_client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_expected_close_date'), ['expected_close_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_status'), ['status'], unique=False)

    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scope_summary', sa.Text(), nullable=True),
    sa.Column('proposed_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_date', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by_email', sa.String(length=255), nullable=True),
    sa.Column('decided_by_name', sa.String(length=255), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_email', sa.String(length=255), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], name=op.f('fk_proposals_prospect_id_prospects')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposals_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposals_prospect_id'), ['prospect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposals_status'), ['status'], unique=False)

    op.create_table('prospect_stage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], name=op.f('fk_prospect_stage_events_prospect_id_prospects')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prospect_stage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prospect_stage_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospect_stage_events_prospect_id'), ['prospect_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prospect_stage_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prospect_stage_events_prospect_id'))
        batch_op.drop_index(batch_op.f('ix_prospect_stage_events_id'))

    op.drop_table('prospect_stage_events')
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_proposals_prospect_id'))
        batch_op.drop_index(batch_op.f('ix_proposals_id'))
        batch_op.drop_index(batch_op.f('ix_proposals_deleted_at'))

    op.drop_table('proposals')
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prospects_status'))
        batch_op.drop_index(batch_op.f('ix_prospects_source'))
        batch_op.drop_index(batch_op.f('ix_prospects_industry'))
        batch_op.drop_index(batch_op.f('ix_prospects_id'))
        batch_op.drop_index(batch_op.f('ix_prospects_expected_close_date'))
        batch_op.drop_index(batch_op.f('ix_prospects_department_id'))
        batch_op.drop_index(batch_op.f('ix_prospects_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_prospects_converted_client_id'))
        batch_op.drop_index(batch_op.f('ix_prospects_contact_email'))
        batch_op.drop_index(batch_op.f('ix_prospects_company_name'))
        batch_op.drop_index(batch_op.f('ix_prospects_assigned_to_user_id'))

    op.drop_table('prospects')
    # ### end Alembic commands ###
