"""add engagement risk snapshots and document extractions

Revision ID: 9afebef7a33f
Revises: c162202f9309
Create Date: 2026-08-21 08:01:57.872819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9afebef7a33f'
down_revision: Union[str, Sequence[str], None] = 'c162202f9309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagement_risk_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('current_health', sa.String(length=10), nullable=False),
    sa.Column('predicted_health', sa.String(length=10), nullable=False),
    sa.Column('overdue_task_count', sa.Integer(), nullable=False),
    sa.Column('percent_budget_consumed', sa.Integer(), nullable=True),
    sa.Column('signals', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_engagement_risk_snapshots_project_id_projects')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engagement_risk_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engagement_risk_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagement_risk_snapshots_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagement_risk_snapshots_snapshot_date'), ['snapshot_date'], unique=False)

    op.create_table('document_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_record_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amounts', sa.Text(), nullable=True),
    sa.Column('dates', sa.Text(), nullable=True),
    sa.Column('labeled_figures', sa.Text(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('extracted_by_email', sa.String(length=255), nullable=False),
    sa.Column('extracted_by_name', sa.String(length=255), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_record_id'], ['file_records.id'], name=op.f('fk_document_extractions_file_record_id_file_records')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_extractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_extractions_file_record_id'), ['file_record_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_document_extractions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_extractions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_extractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_extractions_status'))
        batch_op.drop_index(batch_op.f('ix_document_extractions_id'))
        batch_op.drop_index(batch_op.f('ix_document_extractions_file_record_id'))

    op.drop_table('document_extractions')
    with op.batch_alter_table('engagement_risk_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engagement_risk_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_engagement_risk_snapshots_project_id'))
        batch_op.drop_index(batch_op.f('ix_engagement_risk_snapshots_id'))

    op.drop_table('engagement_risk_snapshots')
    # ### end Alembic commands ###
