"""add standard_weekly_hours to users for capacity forecasting

Revision ID: b0a3248de0db
Revises: 9afebef7a33f
Create Date: 2026-08-22 14:18:58.896705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0a3248de0db'
down_revision: Union[str, Sequence[str], None] = '9afebef7a33f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'standard_weekly_hours',
                sa.Numeric(precision=5, scale=2),
                nullable=False,
                server_default='40',
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('standard_weekly_hours')

    # ### end Alembic commands ###
