"""add signature envelopes and change order signature tracking

Revision ID: c162202f9309
Revises: 46ff272cb72b
Create Date: 2026-08-20 22:54:35.102142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c162202f9309'
down_revision: Union[str, Sequence[str], None] = '46ff272cb72b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signature_envelopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_envelope_id', sa.String(length=255), nullable=False),
    sa.Column('signer_email', sa.String(length=255), nullable=False),
    sa.Column('signer_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('declined_at', sa.DateTime(), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('requested_by_email', sa.String(length=255), nullable=False),
    sa.Column('requested_by_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signature_envelopes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signature_envelopes_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_envelopes_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_envelopes_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_envelopes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_envelopes_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_envelopes_provider_envelope_id'), ['provider_envelope_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_signature_envelopes_status'), ['status'], unique=False)

    with op.batch_alter_table('change_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('signed_at', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_change_orders_signature_status'), ['signature_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_orders_signature_status'))
        batch_op.drop_column('signed_at')
        batch_op.drop_column('signature_status')

    with op.batch_alter_table('signature_envelopes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signature_envelopes_status'))
        batch_op.drop_index(batch_op.f('ix_signature_envelopes_provider_envelope_id'))
        batch_op.drop_index(batch_op.f('ix_signature_envelopes_project_id'))
        batch_op.drop_index(batch_op.f('ix_signature_envelopes_id'))
        batch_op.drop_index(batch_op.f('ix_signature_envelopes_document_type'))
        batch_op.drop_index(batch_op.f('ix_signature_envelopes_document_id'))
        batch_op.drop_index(batch_op.f('ix_signature_envelopes_deleted_at'))

    op.drop_table('signature_envelopes')
    # ### end Alembic commands ###
