"""add contacts contracts task enhancements milestones and project file scoping

Revision ID: dd16b268bb45
Revises: f86923b5c203
Create Date: 2026-08-14 23:05:39.069449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd16b268bb45'
down_revision: Union[str, Sequence[str], None] = 'f86923b5c203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('engagement_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_email', sa.String(length=255), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_templates_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_templates_engagement_type'), ['engagement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_templates_id'), ['id'], unique=False)

    op.create_table('task_template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('relative_due_days', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['task_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_template_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_template_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_template_items_template_id'), ['template_id'], unique=False)

    op.create_table('client_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_contacts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_contacts_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_contacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_contacts_is_primary'), ['is_primary'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('billing_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_email', sa.String(length=255), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_billing_type'), ['billing_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_status'), ['status'], unique=False)

    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_email', sa.String(length=255), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_status'), ['status'], unique=False)

    op.create_table('task_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_task_id', name='uq_task_dependency_pair')
    )
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_dependencies_depends_on_task_id'), ['depends_on_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependencies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependencies_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('relationship_health', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_clients_parent_client_id'), ['parent_client_id'], unique=False)
        batch_op.create_foreign_key("fk_clients_parent_client_id_clients", "clients", ["parent_client_id"], ["id"])

    with op.batch_alter_table('file_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_file_records_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key("fk_file_records_project_id_projects", "projects", ["project_id"], ["id"])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_task_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recurrence_rule', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('recurrence_end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('recurrence_parent_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_parent_task_id'), ['parent_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_recurrence_parent_id'), ['recurrence_parent_id'], unique=False)
        batch_op.create_foreign_key("fk_tasks_recurrence_parent_id_tasks", "tasks", ["recurrence_parent_id"], ["id"])
        batch_op.create_foreign_key("fk_tasks_parent_task_id_tasks", "tasks", ["parent_task_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint("fk_tasks_parent_task_id_tasks", type_='foreignkey')
        batch_op.drop_constraint("fk_tasks_recurrence_parent_id_tasks", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_recurrence_parent_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_parent_task_id'))
        batch_op.drop_column('recurrence_parent_id')
        batch_op.drop_column('recurrence_end_date')
        batch_op.drop_column('recurrence_rule')
        batch_op.drop_column('parent_task_id')

    with op.batch_alter_table('file_records', schema=None) as batch_op:
        batch_op.drop_constraint("fk_file_records_project_id_projects", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_file_records_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint("fk_clients_parent_client_id_clients", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_clients_parent_client_id'))
        batch_op.drop_column('relationship_health')
        batch_op.drop_column('parent_client_id')

    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_dependencies_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependencies_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependencies_depends_on_task_id'))

    op.drop_table('task_dependencies')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_status'))
        batch_op.drop_index(batch_op.f('ix_milestones_project_id'))
        batch_op.drop_index(batch_op.f('ix_milestones_id'))
        batch_op.drop_index(batch_op.f('ix_milestones_due_date'))
        batch_op.drop_index(batch_op.f('ix_milestones_deleted_at'))

    op.drop_table('milestones')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_status'))
        batch_op.drop_index(batch_op.f('ix_contracts_project_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_contracts_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_contracts_billing_type'))

    op.drop_table('contracts')
    with op.batch_alter_table('client_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_contacts_is_primary'))
        batch_op.drop_index(batch_op.f('ix_client_contacts_id'))
        batch_op.drop_index(batch_op.f('ix_client_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_client_contacts_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_client_contacts_client_id'))

    op.drop_table('client_contacts')
    with op.batch_alter_table('task_template_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_template_items_template_id'))
        batch_op.drop_index(batch_op.f('ix_task_template_items_id'))

    op.drop_table('task_template_items')
    with op.batch_alter_table('task_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_templates_id'))
        batch_op.drop_index(batch_op.f('ix_task_templates_engagement_type'))
        batch_op.drop_index(batch_op.f('ix_task_templates_deleted_at'))

    op.drop_table('task_templates')
    # ### end Alembic commands ###
